### ISSUE TITLE
Word saving every time users clicks Yes/No on card word is saving

### ISSUE THREAD

**Issue by shivamdixit** [ashishmadeti/zinger#16]
Every time the user is clicking yes or no on flashcard, word is getting saved. Is it only the debug message, that even for updating the count of the word it is showing "Saved key" or the word is really storing every time?

Refer screenshot:

![bug](https://cloud.githubusercontent.com/assets/3061095/6044648/b92738e4-acba-11e4-9888-eed26daa26d1.png)

**Comment by ashishmadeti** [comment]
The word is saved (rather updated) because when a user clicks yes or no, the count is getting updated.
