### ISSUE TITLE
Don't show meaning if double click is on a single letter

### ISSUE THREAD

**Issue by shivamdixit** [ashishmadeti/zinger#20]
Makes sense?

**Comment by ashishmadeti** [comment]
And on two letters?

**Comment by shivamdixit** [comment]
I'm talking about these cases:

![bug](https://cloud.githubusercontent.com/assets/3061095/6074470/ec4cc8d0-ade4-11e4-9916-5cbb1cc1bd86.png)

I think two letter is fine. Because there ARE some words which are two letter long.

**Comment by ashishmadeti** [comment]
It should not work on special characters anyway.
List those 2 letter words and you'll understand if they are worth showing as a flashcard.

**Comment by shivamdixit** [comment]
Here is a complete [list](http://www.oxforddictionaries.com/words/two-letter-words) of two letter words. We never know if the user don't know meaning of these words. He might be a new english learner.

**Comment by shivamdixit** [comment]
So lets leave it on the user. We should just filter out words which contain special symbol.
