### ISSUE TITLE
Flashcard hides on clicking

### ISSUE THREAD

**Issue by shivamdixit** [ashishmadeti/zinger#25]
Sometimes on clicking the card for first time (i.e on a new page) it hides. I'm not able to find the exact case in which it is happening so cannot provide steps to reproduce it. Please keep a track, if it is happening with you guys also try to reproduce it.

**Comment by RiteshAgrawal** [comment]
Steps to reproduce:
1. Open shivamdixit.com.
2. Scroll down a bit.
3. Double click on flashcard.
It moves on top at -662px location.
![screenshot](https://cloud.githubusercontent.com/assets/6443008/6096032/4698d730-afa1-11e4-8460-d25bace0d284.png)

**Comment by shivamdixit** [comment]
Hence the card is moving to top left most corner. And on moving it speedily the card attains unrealistic top position so the card appears to be hidden.

Therefore the bug is duplicate of #10
