### ISSUE TITLE
Error in getContext on shivamdixit.com

### ISSUE THREAD

**Issue by shivamdixit** [ashishmadeti/zinger#31]
Not coming on other sites. Is it a word specific word or site specific?
I'm not able to reproduce it on other websites.

![bug](https://cloud.githubusercontent.com/assets/3061095/6095365/b374110c-af7f-11e4-9272-1587d1855a73.png)

**Comment by RiteshAgrawal** [comment]
Provide steps to reproduce.

**Comment by shivamdixit** [comment]
Just open the website.

**Comment by RiteshAgrawal** [comment]
Unable to reproduce.

**Comment by shivamdixit** [comment]
The bug is no more reproducible.
