### ISSUE TITLE
Extension interfering with Gmail's css

### ISSUE THREAD

**Issue by shivamdixit** [ashishmadeti/zinger#44]
Check out the gmail.com when extension is enabled. I'm not sure which commit introduced this bug.

@ashishmadeti Can you help me with bisecting?

**Comment by ashishmadeti** [comment]
22db2a7c1f0107402a7bf7b20f94415ba8e10ca6 is the first bad commit
Fixes #43. Added enscroll for scrolling in flashcard. Improved CSS

**Comment by shivamdixit** [comment]
Thanks @ashishmadeti. I'm working on it.

**Comment by shivamdixit** [comment]
Issue is in the enscroll library itself. Merely including the library is causing the problem. What do you think we should do?

**Comment by shivamdixit** [comment]
@ashishmadeti First bad commit is 1ed4787bb58497854953b19a80ccaa511bb02b52, not 22db2a7c1f0107402a7bf7b20f94415ba8e10ca6

**Comment by ashishmadeti** [comment]
I guess you stopped at "0 revisions left to test after this", if you see,
that commit was good and if you mark it so, it will give you the bad commit.

**Comment by ashishmadeti** [comment]
Or maybe and I was wrong, due to which you learned bisecting :P

**Comment by shivamdixit** [comment]
Actually I din't bisect the code at all. All I did was manual inspection and found out the bad commit :wink:
